Initial code with webpack and folder structure
Attila00/Training_Shopping_Cart_new pull request #1
Opened 2021-05-04 11:53 UTC by Attila00

Base boilerplate code with webpack configuration.

2021-05-08 18:12 UTC, salilkapoor requested changes
We can discuss further on these points.
There are a lot many static images pushed in from that point of view.

Even Webpack config is not complete.

styling setup is complete, will discuss on folder structure

2021-05-08 18:12 UTC, salilkapoor commented on public/index.html
> +    <title>React and Webpack</title>
Change title as per requirement in next PR's.

2021-05-08 18:12 UTC, salilkapoor commented on src/components/App.js
> +import '../css/main.scss';
css?? Let's discuss on this

2021-05-08 18:12 UTC, salilkapoor commented on src/components/atoms/Image.js
> +    return <img src={source} alt="" />
image must accept props for URL & alt

alt is very important from the Accessibility point of view

try using prop-types and defining prop types

2021-05-08 18:12 UTC, salilkapoor commented on src/css/main.scss
> +}
move component styles with the component

2021-05-08 18:12 UTC, salilkapoor commented on src/css/main.scss
> +}
define tokens, I think these styles are just dummy.

2021-05-08 18:12 UTC, salilkapoor commented on src/static/images/cart.svg
> +<?xml version="1.0" encoding="utf-8"?>
let's discuss static assets folder + we can think of creating a component for svg's

2021-05-08 18:12 UTC, salilkapoor commented on webpack.config.js
> +                 test:/\.js$/,
add jsx

2021-05-08 18:12 UTC, salilkapoor commented on src/components/Header.js
> +    return <></>
Component type??

2021-05-13 16:39 UTC, salilkapoor requested changes

2021-05-13 16:39 UTC, salilkapoor commented on src/App.js
> +import {Route, Switch, BrowserRouter as Router} from 'react-router-dom';
Switch ?? Route ??

2021-05-13 16:39 UTC, salilkapoor commented on src/components/atoms/CardText.js
> +        <div><Button name={content.buttonName} type="primary"></Button></div>
why div container??

2021-05-13 16:39 UTC, salilkapoor commented on src/components/atoms/Button.js
> +    buttonstyle = props.type === "primary" ? {...buttonstyle , "background-color":"red"} : {...buttonstyle, "background-color":"blue"}
if you want to use styles in js then prefer styled components, don't give inline styles like this.

Secondly, the meaning of atom is getting lost.

2021-05-13 16:39 UTC, salilkapoor commented on src/components/Organisms/header/Header.js
> +            <div className="header__navhome">
nav can be semantically correct here, secondly, this can be further broken down into components.

2021-05-13 16:39 UTC, salilkapoor commented on src/components/Organisms/header/Header.js
> +            <Icon source="../../../assets/images/logo.png" alt="Application Logo"/>
prefer to create locale file.

2021-05-13 16:39 UTC, salilkapoor commented on src/components/Organisms/header/Header.js
> +        <div className="header__subheader">
sub-container?? why required?

2021-05-13 16:39 UTC, salilkapoor commented on src/components/Organisms/header/Header.js
> +            <div className="header__navhome">
class names can be improved &__navhome_item -> &__nav-item__home-link

2021-05-13 16:39 UTC, salilkapoor commented on src/components/Organisms/header/Header.js
> +            <div className="header__navhome">
locale can be maintained for text

2021-05-13 16:39 UTC, salilkapoor commented on src/components/Organisms/Section.js
> +            {categories.map((category, index) => {
I need to discuss this as you are conditionally returning.

2021-05-18 13:56 UTC, merged

2021-05-19 04:54 UTC, Attila00 commented on src/App.js
> +import {Route, Switch, BrowserRouter as Router} from 'react-router-dom';
Switch and Route are being imported and used for the purpose of routing in the application.

2021-05-19 04:56 UTC, Attila00 commented on src/components/atoms/CardText.js
> +        <div><Button name={content.buttonName} type="primary"></Button></div>
Have updated the generic div tag to a more relevant semantic HTML tag of 'aside'.

2021-05-19 04:58 UTC, Attila00 commented on src/components/atoms/Button.js
> +    buttonstyle = props.type === "primary" ? {...buttonstyle , "background-color":"red"} : {...buttonstyle, "background-color":"blue"}
Updated the button atom by removing all inline styles.

2021-05-19 05:15 UTC, Attila00 commented on src/components/Organisms/header/Header.js
> +            <div className="header__navhome">
Have updated nav semantic and classnames. Setup is in progress for locale and multilingual.

2021-05-19 05:16 UTC, Attila00 commented on src/components/Organisms/header/Header.js
> +            <Icon source="../../../assets/images/logo.png" alt="Application Logo"/>
Setup is in progress for locale and multilingual.

2021-05-19 05:17 UTC, Attila00 commented on src/components/Organisms/header/Header.js
> +        <div className="header__subheader">
As amongst the complete header, a subsection of a particular width is required, which will be smaller than the header when screen size increases to a certain extent.